server:
  port: 8081

spring:
  application:
    name: ASSD

camunda:
  client:
    mode: self-managed
    auth:
      method: oidc
      client-id: assd
      client-secret: BDMn8BRThR05Q3aB0vEbli195bCBFQss
      issuer-url: http://host.docker.internal:18080/auth/realms/camunda-platform
      audience: camunda-platform
      scope: openid profile email
    grpc-address: http://host.docker.internal:26500
    rest-address: http://host.docker.internal:8080
    worker:
      default-name: ${spring.application.name}-worker
      auto-startup: true
      default-type: spring-boot

logging:
  level:
    io.camunda.zeebe.client: DEBUG
    com.example.camunda: DEBUG
