server:
  port: 8080

spring:
  application:
    name: camunda-job-workers

camunda:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true
    worker:
      default-name: capability-worker
      auto-startup: true

logging:
  level:
    io.camunda.zeebe.client: DEBUG
    com.example.camunda: DEBUG
